version: '3.1'

services:

  db:
    image: hypriot/rpi-mysql:5.5
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - dbdata:/var/lib/mysql

  web:
    image: nginx:1.21.6-alpine
    restart: always
    depends_on:
      - db
      - php
    links:
      - php
    volumes:
      - ./Website:/srv/http
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"  # restart server

  php:
    image: php:fpm
    command: bash -c "docker-php-ext-install pdo pdo_mysql && php-fpm"
    restart: always
    links:
      - db
    volumes:
      - ./Website:/srv/http
      - ./php.ini:/usr/local/etc/php/php.ini

volumes:
  dbdata: